version: '3'

services:
  lucabazza_git:
    image: httpd:2.4-alpine
    volumes:
      - .:/usr/local/apache2/htdocs/
    ports:
      - 80:80

# guide:  
#   1- cd percorso
#   2- docker-compose up
#   3- go to http://localhost:80/