version: '3'

services:
  lucabazza.github.io:
    #image: httpd:2.4-alpine
    #volumes:
    #  - .:/usr/local/apache2/htdocs/
    image: nginx:1.25.3-alpine3.18-perl
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

# guide:  
#   1- cd percorso
#   2- docker-compose up
#   3- go to http://localhost:80/

# docker build -t lucabazza.github.io .
# docker run -d --name lucabazza.github.io -p 88:80 -d lucabazza.github.io