version: '3'
services:
  web:
    #build: /Users/lucabazzanella/Desktop/nodeJS_docker/dist/
    build: #/Users/lucabazzanella/Desktop/nodeJS_docker/
      context: .
      dockerfile: Dockerfile
      #labels:
      # com.example.description: "zabba_nodejs"
    container_name: zabba_nodejs
    ports:
      - "8080:8080"
    volumes: 
     - "/Users/lucabazzanella/Desktop/nodeJS_docker:/dist/"
      